version: '3.4'

services:
  pulp:
    build: .
    command: yarn run pulp --watch build --to dist/pure.js
    volumes:
      - ./:/apps/pure

  parcel:
    build:
      context: .
      dockerfile: Dockerfile.parcel
    command: npx parcel index.html --cache-dir .parcel-cache --hmr-port 39303
    ports:
      - '1234:1234'
      - '39303:39303'
    volumes:
      - ./:/apps/pure
